# Site settings
title: "Modestas Kažinauskas"
email: m.kazinauskas@gmail.com
author: Modestas Kažinauskas
description: "Blog about technology, development and soft skills"
github_username: mkazinauskas
baseurl: "/blog"
url: "https://mkazinauskas.github.io"
google_analytics: "UA-169701976-2"
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
sass:
  compressed: true

gems:
  - jekyll-paginate
  - jekyll-redirect-from

kramdown:
  input: GFM
  syntax_highlighter: rouge
